In [1]:
import torch

In [2]:
print(torch.__version__)

1.13.1+cu116


## Tensors

Summing it up: 
* Scalar - a number - dim 0
* Vector - a row of entities - dim 1
* Matrix - a combination of rows and columns - dim 2
* Tensor - a collection of matrices - dim 3

In general, as the dimension increases, it is just the earlier dimension representated as collection in a different format

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:

scalar.item()

7

In [8]:
vector = torch.tensor([5,6,7])
vector

tensor([5, 6, 7])

In [10]:
vector.ndim

1

In [11]:
vector.item()

ValueError: ignored

🔴 item() method works for only scalars

In [15]:
vector.shape

torch.Size([3])

In [17]:
matrix = torch.tensor([[1,2],[3,4]])

In [18]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

In [19]:
assert matrix.ndim == len(matrix.shape[:])

In [31]:
tensor = torch.tensor([
    [
        [1,1], 
        [1,1], 
        [2,3]
     ],
    [
        [2,2], 
        [2,2],
        [2,2]
     ]
     ])

In [32]:
tensor.ndim, tensor.shape

(3, torch.Size([2, 3, 2]))

🎃 Shape goes from outer to inner

Some standard methods of creating tensors
* rand(size)
* zeros(size)
* ones(size)
* arange(start,end, step)

Two new methods
* zeros_like(input)
* ones_like(input)

In [35]:
random_tensor = torch.rand(size = (1,3,2))

In [36]:
random_tensor

tensor([[[0.9013, 0.3610],
         [0.9183, 0.5964],
         [0.8409, 0.9902]]])

In [37]:
one_tensor = torch.ones(size = (7,1,1))

zero_tensor = torch.zeros(size = (4,3,4))

In [ ]:
one_tensor

In [ ]:
zero_tensor

In [40]:
range_tensor = torch.arange(0,10,3)

In [42]:
range_tensor

tensor([0, 3, 6, 9])

In [43]:
four_zeros_tensor = torch.zeros_like(input = range_tensor)

In [44]:
four_zeros_tensor

tensor([0, 0, 0, 0])

Datatypes: 
Common issues with datatypes are
* precision mismatch
* device mismatch 

In [45]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.device)

tensor([[0.9954, 0.3814, 0.4561, 0.9402],
        [0.7991, 0.5719, 0.9564, 0.1230],
        [0.4926, 0.4247, 0.9970, 0.4306]])
torch.float32
cpu


Operations on Tensors

In [46]:
tensor = torch.tensor([ 7, 12, 18])
tensor + 10

tensor([17, 22, 28])

In [47]:
tensor * 10 

tensor([ 70, 120, 180])

In [48]:
tensor - 10

tensor([-3,  2,  8])

In [49]:
tensor.shape

torch.Size([3])

In [50]:
torch.matmul(torch.rand(size = (2,3)), torch.rand(size = (3,2)))

tensor([[0.8573, 0.8799],
        [0.9027, 0.8034]])

In [51]:
torch.mm(torch.rand(size = (2,3)), torch.rand(size = (3,2)))

tensor([[0.4681, 0.4027],
        [0.6711, 0.3398]])

Reshaping, Stacking, Squeezing and Unsqueezing

In [54]:
x = torch.arange(7,15)
x

tensor([ 7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
x.reshape(2,4)

tensor([[ 7,  8,  9, 10],
        [11, 12, 13, 14]])

In [56]:
x.view(4,2)

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]])

In [59]:
torch.stack([x, x, x], dim = -1)

tensor([[ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12],
        [13, 13, 13],
        [14, 14, 14]])

In [65]:
y = torch.rand(size = (4,3, 1, 1))

In [ ]:
y

In [67]:
y.squeeze()

tensor([[0.8452, 0.5224, 0.5313],
        [0.0527, 0.4518, 0.7368],
        [0.5013, 0.1564, 0.6460],
        [0.7403, 0.7691, 0.0330]])

In [70]:
y.unsqueeze(dim = 3)

tensor([[[[[0.8452]]],


         [[[0.5224]]],


         [[[0.5313]]]],



        [[[[0.0527]]],


         [[[0.4518]]],


         [[[0.7368]]]],



        [[[[0.5013]]],


         [[[0.1564]]],


         [[[0.6460]]]],



        [[[[0.7403]]],


         [[[0.7691]]],


         [[[0.0330]]]]])

In [71]:
y.shape

torch.Size([4, 3, 1, 1])

Numpy with Pytorch
* torch.from_numpy(ndarray)
* torch.Tensor.numpy() 

In [69]:
import numpy as np

array = np.arange(2.4, 7.0, 0.9)

tensor = torch.from_numpy(array)

array, tensor

(array([2.4, 3.3, 4.2, 5.1, 6. , 6.9]),
 tensor([2.4000, 3.3000, 4.2000, 5.1000, 6.0000, 6.9000], dtype=torch.float64))

In [72]:
tensor.numpy()

array([2.4, 3.3, 4.2, 5.1, 6. , 6.9])

In [77]:
assert type(array) == type(tensor.numpy())

Reproducing results

* torch.manual_seed() to set seed 
* We need to use it every time when we use random functions

In [79]:
torch.manual_seed(seed = 42)
random_tensor_C = torch.rand(4,3)

torch.random.manual_seed( seed = 42)
random_tensor_E = torch.rand(4,3)

random_tensor_C == random_tensor_E

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

We can move tensors to CPU and GPU depending on our resources